# Generated by Django 4.0.4 on 2022-05-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=150)),
                ('apellidos', models.TextField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('ranking', models.IntegerField()),
                ('equipos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GarciaFutbolitis.equipos')),
            ],
        ),
    ]
